version: '2'
services:
    jhipster-app:
        image: jhipster
        external_links:
            - jhipster-mysql:mysql
            - jhipster-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
    jhipster-mysql:
        extends:
            file: mysql.yml
            service: jhipster-mysql
    jhipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipster-elasticsearch
