
server:
  port: 8080

oidc-google:
  client:
    id: 1074069313096-en54stnpso957k58jt1mge0ih1ksl3lr.apps.googleusercontent.com
    secret: c3yg7pJO8aVRgYEawI0TJba1
  token:
    issuer: accounts.google.com
    jwkurl: https://www.googleapis.com/oauth2/v1/certs
  accessTokenUri: https://oauth2.googleapis.com/token
  userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
  redirectUri: http://localhost:9100/oidc_auth
  userInfoUri: https://www.googleapis.com/userinfo/v2/me

oidc:
  client:
    id: 233668646673605
    secret: 33b17e044ee6a4fa383f46ec6e28ea1d
  token:
    issuer: facebook.com
    jwkurl: https://www.googleapis.com/oauth2/v1/certs
    name: oauth_token
  authenticationScheme: query
  clientAuthenticationScheme: form
  accessTokenUri: https://graph.facebook.com/oauth/access_token
  userAuthorizationUri: https://www.facebook.com/dialog/oauth
  redirectUri: http://localhost:8080/oidc_auth
  userInfoUri: https://graph.facebook.com/me


logging:
  level:
    com.digvijayb.oauth.client: DEBUG